#!/bin/sh
PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

for f in $(find /lib/firmware/qcom/x1e80100 -type f); do
        add_firmware "${f#/lib/firmware/}"
done
